[package]
name = "planet_material"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13", features = ["file_watcher"] }
bevy_shader_utils = "0.7.0"
bevy_panorbit_camera = "0.18"
rand = "0.8.5"
noise = "0.9.0"
